/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controlar.ControladorDeUsuario;
import java.io.File;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import modelo.Usuario;
import utilidade.Util;

/**
 *
 * @author aluno.saolucas
 */
public class FrCadastrar extends javax.swing.JFrame {

    /**
     * Creates new form FrCadastrar
     */
    public FrCadastrar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlSecundario = new javax.swing.JPanel();
        lblCadastrar = new javax.swing.JLabel();
        btnEscolherImagem = new javax.swing.JButton();
        lblSenha = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblRepetirSenha = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblObjetivo = new javax.swing.JLabel();
        edtObjetivo = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        edtTelefone = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        pnlFoto = new javax.swing.JPanel();
        imgFoto = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        edtCpf = new javax.swing.JFormattedTextField();
        chkAtivo = new javax.swing.JCheckBox();
        edtConfirmarSenha = new javax.swing.JPasswordField();
        edtSenha = new javax.swing.JPasswordField();
        edtDataNascimento = new javax.swing.JFormattedTextField();
        btnCadastrar = new javax.swing.JButton();
        lblLogar = new javax.swing.JLabel();
        iconLogar = new javax.swing.JLabel();
        lblTextoLogar3 = new javax.swing.JLabel();
        lblTextoLogar2 = new javax.swing.JLabel();
        lblTextoLogar1 = new javax.swing.JLabel();
        btnLogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Cadastro - FitZone");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSecundario.setBackground(new java.awt.Color(251, 186, 0));
        pnlSecundario.setPreferredSize(new java.awt.Dimension(740, 720));
        pnlSecundario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCadastrar.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lblCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        lblCadastrar.setText("CADASTRAR");
        pnlSecundario.add(lblCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        btnEscolherImagem.setBackground(new java.awt.Color(255, 255, 255));
        btnEscolherImagem.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnEscolherImagem.setForeground(new java.awt.Color(0, 0, 0));
        btnEscolherImagem.setText("ESCOLHER IMAGEM");
        btnEscolherImagem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnEscolherImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEscolherImagemMouseClicked(evt);
            }
        });
        btnEscolherImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolherImagemActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnEscolherImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 160, 50));

        lblSenha.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblSenha.setText("Senha");
        pnlSecundario.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        edtEmail.setBackground(new java.awt.Color(255, 255, 255));
        edtEmail.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtEmail.setForeground(java.awt.Color.black);
        edtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEmail.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEmail.setPreferredSize(new java.awt.Dimension(10, 20));
        edtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEmailActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 640, 50));

        lblEmail.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText("E-Mail");
        pnlSecundario.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        edtNome.setBackground(new java.awt.Color(255, 255, 255));
        edtNome.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtNome.setForeground(java.awt.Color.black);
        edtNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtNome.setMinimumSize(new java.awt.Dimension(10, 20));
        edtNome.setPreferredSize(new java.awt.Dimension(10, 20));
        edtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 640, 50));

        lblNome.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome");
        pnlSecundario.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        lblRepetirSenha.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblRepetirSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblRepetirSenha.setText("Confirmar Senha");
        pnlSecundario.add(lblRepetirSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        lblDataNascimento.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblDataNascimento.setForeground(new java.awt.Color(0, 0, 0));
        lblDataNascimento.setText("Data Nascimento");
        pnlSecundario.add(lblDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, -1, -1));

        lblObjetivo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblObjetivo.setForeground(new java.awt.Color(0, 0, 0));
        lblObjetivo.setText("Objetivo");
        pnlSecundario.add(lblObjetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, -1, -1));

        edtObjetivo.setBackground(new java.awt.Color(255, 255, 255));
        edtObjetivo.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtObjetivo.setForeground(java.awt.Color.black);
        edtObjetivo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtObjetivo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtObjetivo.setMinimumSize(new java.awt.Dimension(10, 20));
        edtObjetivo.setPreferredSize(new java.awt.Dimension(10, 20));
        edtObjetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtObjetivoActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtObjetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 210, 50));

        lblCpf.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(0, 0, 0));
        lblCpf.setText("CPF");
        pnlSecundario.add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        edtTelefone.setBackground(new java.awt.Color(255, 255, 255));
        edtTelefone.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtTelefone.setForeground(java.awt.Color.black);
        edtTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtTelefone.setMinimumSize(new java.awt.Dimension(10, 20));
        edtTelefone.setPreferredSize(new java.awt.Dimension(10, 20));
        edtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTelefoneActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 210, 50));

        lblTelefone.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefone.setText("Telefone");
        pnlSecundario.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        pnlFoto.setBackground(new java.awt.Color(255, 255, 255));
        pnlFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlFotoLayout = new javax.swing.GroupLayout(pnlFoto);
        pnlFoto.setLayout(pnlFotoLayout);
        pnlFotoLayout.setHorizontalGroup(
            pnlFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoLayout.createSequentialGroup()
                .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlFotoLayout.setVerticalGroup(
            pnlFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoLayout.createSequentialGroup()
                .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlSecundario.add(pnlFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 100, 133));
        pnlFoto.getAccessibleContext().setAccessibleName("");

        btnLimpar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpar.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar.png"))); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
        });
        pnlSecundario.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, 180, 50));

        edtCpf.setBackground(new java.awt.Color(255, 255, 255));
        edtCpf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtCpf.setForeground(java.awt.Color.black);
        try {
            edtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtCpf.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCpfActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 210, 50));

        chkAtivo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        chkAtivo.setText("ATIVO");
        pnlSecundario.add(chkAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, -1, 50));

        edtConfirmarSenha.setBackground(new java.awt.Color(255, 255, 255));
        edtConfirmarSenha.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtConfirmarSenha.setForeground(new java.awt.Color(0, 0, 0));
        edtConfirmarSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlSecundario.add(edtConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 210, 50));

        edtSenha.setBackground(new java.awt.Color(255, 255, 255));
        edtSenha.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtSenha.setForeground(new java.awt.Color(0, 0, 0));
        edtSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlSecundario.add(edtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 210, 50));

        edtDataNascimento.setBackground(new java.awt.Color(255, 255, 255));
        edtDataNascimento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtDataNascimento.setForeground(java.awt.Color.black);
        edtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        edtDataNascimento.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDataNascimentoActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 210, 50));

        btnCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar.png"))); // NOI18N
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        pnlSecundario.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 640, 220, 50));

        pnlPrincipal.add(pnlSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 860, 720));

        lblLogar.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lblLogar.setForeground(new java.awt.Color(0, 0, 0));
        lblLogar.setText("LOGAR");
        pnlPrincipal.add(lblLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        iconLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perfilLogar.png"))); // NOI18N
        pnlPrincipal.add(iconLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        lblTextoLogar3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTextoLogar3.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoLogar3.setText("entre na sua agora mesmo.");
        lblTextoLogar3.setToolTipText("");
        pnlPrincipal.add(lblTextoLogar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 320, 40));

        lblTextoLogar2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTextoLogar2.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoLogar2.setText("Clique no botão abaixo e");
        lblTextoLogar2.setToolTipText("");
        pnlPrincipal.add(lblTextoLogar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 290, 40));

        lblTextoLogar1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTextoLogar1.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoLogar1.setText("Opa! Você já possui a sua conta?");
        lblTextoLogar1.setToolTipText("");
        pnlPrincipal.add(lblTextoLogar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 410, 50));

        btnLogar.setBackground(new java.awt.Color(251, 186, 0));
        btnLogar.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnLogar.setForeground(new java.awt.Color(0, 0, 0));
        btnLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chave.png"))); // NOI18N
        btnLogar.setText("LOGAR");
        btnLogar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnLogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogarMouseClicked(evt);
            }
        });
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, 150, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogarActionPerformed

    private void edtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmailActionPerformed

    private void edtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeActionPerformed

    private void edtObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtObjetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtObjetivoActionPerformed

    private void edtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTelefoneActionPerformed

    private void btnEscolherImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolherImagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEscolherImagemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(Util.getIcone());
    }//GEN-LAST:event_formWindowOpened

    private void edtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCpfActionPerformed

    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
        limpar();
        
    }//GEN-LAST:event_btnLimparMouseClicked

    private void edtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDataNascimentoActionPerformed

    private void btnEscolherImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscolherImagemMouseClicked

        File arquivo = Util.escolherImagem();

        if (arquivo != null) {
            Icon icone = Util.converterFileToIcon(arquivo);

            Icon iconeNovo = Util.redimensionarImagem(icone, 96, 129);

            imgFoto.setIcon(iconeNovo);
        }
    }//GEN-LAST:event_btnEscolherImagemMouseClicked

    private void btnLogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogarMouseClicked
        new FrLogar().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogarMouseClicked

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
     cadastrar();
    }//GEN-LAST:event_btnCadastrarMouseClicked

    
    private void limpar(){
        edtNome.setText("");
        edtEmail.setText("");
        edtSenha.setText("");
        edtTelefone.setText("");
        edtDataNascimento.setText("");
        edtObjetivo.setText("");
        imgFoto.setIcon(null);
        edtCpf.setText("");
        chkAtivo.setSelected(false);
    }
    
    private void cadastrar() {
        if (!verificarCampos()) {
            return;
        }
        Usuario cliente = new Usuario();
        cliente.setNome(edtNome.getText());
        cliente.setEmail(edtEmail.getText());
        cliente.setSenha(Util.calcularHash(new String(edtSenha.getPassword())));
        cliente.setTelefone(edtTelefone.getText());
        cliente.setDataNascimento(Util.converterStringToDate(edtDataNascimento.getText()));
        cliente.setObjetivo(edtObjetivo.getText());
        cliente.setImagem(imgFoto.getIcon());
        cliente.setCpf(cliente.removerCpf(edtCpf.getText()));
        cliente.setAtivo(chkAtivo.isSelected());

        ControladorDeUsuario controller = new ControladorDeUsuario();
        if (controller.inserir(cliente)) {
            JOptionPane.showMessageDialog(null, "Usuário inserido");
            new FrLogar().setVisible(true);
            this.dispose();
        }
    }

    private boolean verificarCampos() {
        Usuario cliente = new Usuario();
        if (edtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha o campo de nome");
            return false;
        }
        if (edtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha o campo de e-mail");
            return false;
        }
        if (new String(edtSenha.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha o campo de senha");
            return false;
        }
        if (!edtNome.getText().matches("^[\\p{L} ]+$")) {
            JOptionPane.showMessageDialog(null,
                    "O campo 'Nome' possui formato inválido");
            return false;
        }
        if (!edtEmail.getText().matches("^[a-z0-9_.]+@[a-z0-9_.]+.[a-z]+$")) {
            JOptionPane.showMessageDialog(null,
                    "O campo 'Email' possui formato inválido");
            return false;
        }
        if (!edtDataNascimento.getText().matches("^[0-9]{2}/[0-9]{2}/[0-9]{4}$")) {
            JOptionPane.showMessageDialog(null,
                    "O campo 'Data Nascimento' possui formato inválido");
            return false;
        }
        if (new String(edtSenha.getPassword()).length() < 8) {
            JOptionPane.showMessageDialog(null,
                    "A senha deve ser maior que 8 dígitos");
            return false;
        }

        if (cliente.removerCpf(edtCpf.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo do CPF do seu usuario nao pode estar vazio");
            return false;
        }
        if (!(cliente.validarCPF(edtCpf.getText()))) {
            JOptionPane.showMessageDialog(null, "Seu CPF deve ser valido e deve conter 11 numeros, ex: 123.456.789-00");
            return false;
        }
        String senha = new String(edtSenha.getPassword());
        String confirmarSenha = new String(edtConfirmarSenha.getPassword());
        if (!senha.equals(confirmarSenha)) {
            JOptionPane.showMessageDialog(null,
                    "Revise sua senha, pois ambas tem que serem iguais");
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEscolherImagem;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLogar;
    private javax.swing.JCheckBox chkAtivo;
    private javax.swing.JPasswordField edtConfirmarSenha;
    private javax.swing.JFormattedTextField edtCpf;
    private javax.swing.JFormattedTextField edtDataNascimento;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtObjetivo;
    private javax.swing.JPasswordField edtSenha;
    private javax.swing.JTextField edtTelefone;
    private javax.swing.JLabel iconLogar;
    private javax.swing.JLabel imgFoto;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogar;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObjetivo;
    private javax.swing.JLabel lblRepetirSenha;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTextoLogar1;
    private javax.swing.JLabel lblTextoLogar2;
    private javax.swing.JLabel lblTextoLogar3;
    private javax.swing.JPanel pnlFoto;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSecundario;
    // End of variables declaration//GEN-END:variables
}
