/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controlar.ControladorDeTreino;
import controlar.ControladorDeUsuario;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Instrutor;
import modelo.InstrutorLogado;
import modelo.Treino;
import modelo.Usuario;

/**
 *
 * @author eleaa
 */
public class FrCriarTreino extends javax.swing.JFrame {

    /**
     * Creates new form FrCriarTreino
     */
    public FrCriarTreino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        lblCriarTreino = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        edtDuracao = new javax.swing.JTextField();
        lblDuracao = new javax.swing.JLabel();
        edtObjetivo = new javax.swing.JTextField();
        lblObjetivo = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        edtDescricao = new javax.swing.JTextField();
        btnCriar = new javax.swing.JButton();
        cbxUsuarios = new javax.swing.JComboBox<>();
        lblNome = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnAdicionarExercicio = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        lblCriarTreino1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoMenor.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 130));

        lblCriarTreino.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lblCriarTreino.setForeground(new java.awt.Color(251, 80, 0));
        lblCriarTreino.setText("CRIAR TREINO");
        getContentPane().add(lblCriarTreino, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        btnSair.setBackground(new java.awt.Color(255, 102, 102));
        btnSair.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnSair.setForeground(new java.awt.Color(0, 0, 0));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icone sair.png"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 140, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtDuracao.setBackground(new java.awt.Color(251, 80, 0));
        edtDuracao.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtDuracao.setForeground(new java.awt.Color(0, 0, 0));
        edtDuracao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtDuracao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtDuracao.setMinimumSize(new java.awt.Dimension(10, 20));
        edtDuracao.setPreferredSize(new java.awt.Dimension(10, 20));
        edtDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDuracaoActionPerformed(evt);
            }
        });
        jPanel1.add(edtDuracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 480, 50));

        lblDuracao.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblDuracao.setForeground(new java.awt.Color(0, 0, 0));
        lblDuracao.setText("Duracao");
        jPanel1.add(lblDuracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        edtObjetivo.setBackground(new java.awt.Color(251, 80, 0));
        edtObjetivo.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtObjetivo.setForeground(new java.awt.Color(0, 0, 0));
        edtObjetivo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtObjetivo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtObjetivo.setMinimumSize(new java.awt.Dimension(10, 20));
        edtObjetivo.setPreferredSize(new java.awt.Dimension(10, 20));
        edtObjetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtObjetivoActionPerformed(evt);
            }
        });
        jPanel1.add(edtObjetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 480, 50));

        lblObjetivo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblObjetivo.setForeground(new java.awt.Color(0, 0, 0));
        lblObjetivo.setText("Objetivo");
        jPanel1.add(lblObjetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        edtNome.setBackground(new java.awt.Color(251, 80, 0));
        edtNome.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtNome.setForeground(new java.awt.Color(0, 0, 0));
        edtNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtNome.setMinimumSize(new java.awt.Dimension(10, 20));
        edtNome.setPreferredSize(new java.awt.Dimension(10, 20));
        edtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 480, 50));

        lblDescricao.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblDescricao.setForeground(new java.awt.Color(0, 0, 0));
        lblDescricao.setText("Descricao");
        jPanel1.add(lblDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        edtDescricao.setBackground(new java.awt.Color(251, 80, 0));
        edtDescricao.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtDescricao.setForeground(new java.awt.Color(0, 0, 0));
        edtDescricao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtDescricao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtDescricao.setMinimumSize(new java.awt.Dimension(10, 20));
        edtDescricao.setPreferredSize(new java.awt.Dimension(10, 20));
        edtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDescricaoActionPerformed(evt);
            }
        });
        jPanel1.add(edtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 480, 50));

        btnCriar.setBackground(new java.awt.Color(251, 80, 0));
        btnCriar.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnCriar.setText("CRIAR");
        btnCriar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCriarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 120, 50));

        cbxUsuarios.setBackground(new java.awt.Color(251, 80, 0));
        cbxUsuarios.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        cbxUsuarios.setForeground(new java.awt.Color(0, 0, 0));
        cbxUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(cbxUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 210, -1));

        lblNome.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblUsuario.setText("Usuario");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        btnAdicionarExercicio.setBackground(new java.awt.Color(251, 80, 0));
        btnAdicionarExercicio.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnAdicionarExercicio.setText("Adicionar Exercicio");
        btnAdicionarExercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdicionarExercicioMouseClicked(evt);
            }
        });
        jPanel1.add(btnAdicionarExercicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 260, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 590, 560));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background Saude.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 1290, 730));

        lblCriarTreino1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lblCriarTreino1.setForeground(new java.awt.Color(251, 186, 0));
        lblCriarTreino1.setText("CRIAR TREINO");
        getContentPane().add(lblCriarTreino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        new FrMenuInstrutor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void edtDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDuracaoActionPerformed

    private void edtObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtObjetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtObjetivoActionPerformed

    private void edtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeActionPerformed

    private void edtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDescricaoActionPerformed

    private void btnCriarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCriarMouseClicked
        int indexSelecionado = cbxUsuarios.getSelectedIndex();
        Usuario usu = cbxUsuarios.getItemAt(indexSelecionado);
        criar(usu.getPkUsuario());
        
        
        
        Instrutor instrutorLogado = InstrutorLogado.getInstrutorLogado();
        System.out.println(usu.getPkUsuario());
        System.out.println(instrutorLogado.getPkInstrutor());
    }//GEN-LAST:event_btnCriarMouseClicked

    private void cbxUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxUsuariosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ControladorDeUsuario conUsu = new ControladorDeUsuario();

        List<Usuario> lista = conUsu.consultar();

        for (Usuario usu : lista) {
            cbxUsuarios.addItem(usu);

        }
    }//GEN-LAST:event_formWindowOpened

    private void btnAdicionarExercicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarExercicioMouseClicked
         new FrAdicionarExercicio().setVisible(true);
    }//GEN-LAST:event_btnAdicionarExercicioMouseClicked

    private void criar(int id) {
        try {
            Instrutor instrutorLogado = InstrutorLogado.getInstrutorLogado();

            if (instrutorLogado == null) {
                JOptionPane.showMessageDialog(this, "Instrutor não logado!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!validarCampos()) {
                return;
            }

            Treino treino = new Treino();
            treino.setFkUsuario(id);
            treino.setFkInstrutor(instrutorLogado.getPkInstrutor());
            treino.setNome(edtNome.getText().trim());
            treino.setDescricao(edtDescricao.getText().trim());
            treino.setObjetivo(edtObjetivo.getText().trim());

            treino.setDuracao_minutos(Integer.parseInt(edtDuracao.getText().trim()));

            ControladorDeTreino conTre = new ControladorDeTreino();
            if (conTre.criar(treino)) {
                JOptionPane.showMessageDialog(this, "Treino criado com sucesso!");
                new FrCriarTreino().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao criar treino.", "Erro", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Duração deve ser um número válido!",
                    "Erro de Formato",
                    JOptionPane.ERROR_MESSAGE);
            edtDuracao.requestFocus();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Erro inesperado: " + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean validarCampos() {
        if (edtNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome é obrigatório!", "Aviso", JOptionPane.WARNING_MESSAGE);
            edtNome.requestFocus();
            return false;
        }

        if (edtDuracao.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Duração é obrigatória!", "Aviso", JOptionPane.WARNING_MESSAGE);
            edtDuracao.requestFocus();
            return false;
        }

        try {
            int duracao = Integer.parseInt(edtDuracao.getText().trim());
            if (duracao <= 0) {
                JOptionPane.showMessageDialog(this, "Duração deve ser maior que zero!", "Aviso", JOptionPane.WARNING_MESSAGE);
                edtDuracao.requestFocus();
                return false;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Duração deve ser um número!", "Aviso", JOptionPane.WARNING_MESSAGE);
            edtDuracao.requestFocus();
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCriarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCriarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCriarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCriarTreino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrCriarTreino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnAdicionarExercicio;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<Usuario> cbxUsuarios;
    private javax.swing.JTextField edtDescricao;
    private javax.swing.JTextField edtDuracao;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtObjetivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCriarTreino;
    private javax.swing.JLabel lblCriarTreino1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDuracao;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObjetivo;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
