
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controlar.ControladorDeInstrutor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.Instrutor;
import modelo.InstrutorLogado;
import utilidade.Util;

/**
 *
 * @author eleaa
 */
public class FrLogarInstrutor extends javax.swing.JFrame {

    /**
     * Creates new form FrLogarInstrutor
     */
    public FrLogarInstrutor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal4 = new javax.swing.JPanel();
        pnlSecundario4 = new javax.swing.JPanel();
        lblCadastrar4 = new javax.swing.JLabel();
        btnCadastrar4 = new javax.swing.JButton();
        lblTextoCadastrar1 = new javax.swing.JLabel();
        lblTextoCadastrar2 = new javax.swing.JLabel();
        lblTextoCadastrar3 = new javax.swing.JLabel();
        iconCadastrar = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblLogar = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        btnLogar = new javax.swing.JButton();
        iconLogar = new javax.swing.JLabel();
        edtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FitZone - Logar - Instrutor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        pnlPrincipal4.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        pnlPrincipal4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSecundario4.setBackground(new java.awt.Color(251, 80, 0));
        pnlSecundario4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        pnlSecundario4.setPreferredSize(new java.awt.Dimension(740, 720));
        pnlSecundario4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCadastrar4.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lblCadastrar4.setForeground(new java.awt.Color(0, 0, 0));
        lblCadastrar4.setText("Cadastrar");
        pnlSecundario4.add(lblCadastrar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        btnCadastrar4.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrar4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnCadastrar4.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastrar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar.png"))); // NOI18N
        btnCadastrar4.setText("Cadastrar");
        btnCadastrar4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCadastrar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrar4MouseClicked(evt);
            }
        });
        pnlSecundario4.add(btnCadastrar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 220, 50));

        lblTextoCadastrar1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTextoCadastrar1.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoCadastrar1.setText("Opa Instrutor! Ainda não tem uma conta?");
        lblTextoCadastrar1.setToolTipText("");
        pnlSecundario4.add(lblTextoCadastrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 500, 30));

        lblTextoCadastrar2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTextoCadastrar2.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoCadastrar2.setText("Clique no botão abaixo e crie");
        lblTextoCadastrar2.setToolTipText("");
        pnlSecundario4.add(lblTextoCadastrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 340, 40));

        lblTextoCadastrar3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTextoCadastrar3.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoCadastrar3.setText("a sua agora mesmo.");
        lblTextoCadastrar3.setToolTipText("");
        pnlSecundario4.add(lblTextoCadastrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 240, 40));

        iconCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perfilCadastrar.png"))); // NOI18N
        pnlSecundario4.add(iconCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        pnlPrincipal4.add(pnlSecundario4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 640, 720));

        lblSenha.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblSenha.setText("Senha");
        pnlPrincipal4.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        lblLogar.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lblLogar.setForeground(new java.awt.Color(0, 0, 0));
        lblLogar.setText("Logar");
        pnlPrincipal4.add(lblLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        lblEmail.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText("E-Mail");
        pnlPrincipal4.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        edtEmail.setBackground(new java.awt.Color(251, 80, 0));
        edtEmail.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        edtEmail.setForeground(new java.awt.Color(0, 0, 0));
        edtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEmail.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEmail.setPreferredSize(new java.awt.Dimension(10, 20));
        edtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEmailActionPerformed(evt);
            }
        });
        edtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtEmailKeyPressed(evt);
            }
        });
        pnlPrincipal4.add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 480, 50));

        btnLogar.setBackground(new java.awt.Color(251, 80, 0));
        btnLogar.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnLogar.setForeground(new java.awt.Color(0, 0, 0));
        btnLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chave.png"))); // NOI18N
        btnLogar.setText("Logar");
        btnLogar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnLogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogarMouseClicked(evt);
            }
        });
        btnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogarActionPerformed(evt);
            }
        });
        pnlPrincipal4.add(btnLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 150, 50));

        iconLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perfilLogar.png"))); // NOI18N
        pnlPrincipal4.add(iconLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        edtSenha.setBackground(new java.awt.Color(251, 80, 0));
        edtSenha.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        edtSenha.setForeground(new java.awt.Color(0, 0, 0));
        edtSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtSenhaActionPerformed(evt);
            }
        });
        edtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtSenhaKeyPressed(evt);
            }
        });
        pnlPrincipal4.add(edtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 480, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlPrincipal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlPrincipal4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrar4MouseClicked
        new FrCadastrarInstrutor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCadastrar4MouseClicked

    private void edtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmailActionPerformed

    private void btnLogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogarMouseClicked
        logarInstrutor();
    }//GEN-LAST:event_btnLogarMouseClicked

    private void btnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogarActionPerformed

    private void edtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtSenhaActionPerformed

    private void edtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

        }
    }//GEN-LAST:event_edtSenhaKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(Util.getIcone());
    }//GEN-LAST:event_formWindowOpened

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void edtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtEmailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            new FrLogar().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_edtEmailKeyPressed

    private boolean verificarCampos() {
        if (edtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, preencha o campo de E-mail", "Aviso", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (new String(edtSenha.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, preencha o campo de senha", "Aviso", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private void logarInstrutor() {
        if (!verificarCampos()) {
            return;
        }
        String email = edtEmail.getText();
        String senha = Util.calcularHash(new String(edtSenha.getPassword()));
        ControladorDeInstrutor controller = new ControladorDeInstrutor();

        Instrutor instrutor = controller.autenticar(email, senha);
        if (instrutor != null) {
            InstrutorLogado.setInstrutorLogado(instrutor);
            FrMenuInstrutor telaMenu = new FrMenuInstrutor();
            telaMenu.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Instrutor não encontrado", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrLogarInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrLogarInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrLogarInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrLogarInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrLogarInstrutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar4;
    private javax.swing.JButton btnLogar;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JPasswordField edtSenha;
    private javax.swing.JLabel iconCadastrar;
    private javax.swing.JLabel iconLogar;
    private javax.swing.JLabel lblCadastrar4;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogar;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTextoCadastrar1;
    private javax.swing.JLabel lblTextoCadastrar2;
    private javax.swing.JLabel lblTextoCadastrar3;
    private javax.swing.JPanel pnlPrincipal4;
    private javax.swing.JPanel pnlSecundario4;
    // End of variables declaration//GEN-END:variables
}
