/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import java.awt.event.KeyEvent;
import utilidade.Util;

/**
 *
 * @author eleaa
 */
public class FrLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrLogin
     */
    public FrLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlSecundario = new javax.swing.JPanel();
        lblCadastrar1 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        lblTextoCadastrar1 = new javax.swing.JLabel();
        lblTextoCadastrar2 = new javax.swing.JLabel();
        lblTextoCadastrar3 = new javax.swing.JLabel();
        iconCadastrar = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblLogar1 = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        edtSenha = new javax.swing.JTextField();
        edtEmail = new javax.swing.JTextField();
        btnLogar1 = new javax.swing.JButton();
        iconLogar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login - FitZone");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSecundario.setBackground(new java.awt.Color(251, 186, 0));
        pnlSecundario.setPreferredSize(new java.awt.Dimension(740, 720));
        pnlSecundario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCadastrar1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lblCadastrar1.setForeground(new java.awt.Color(0, 0, 0));
        lblCadastrar1.setText("CADASTRAR");
        pnlSecundario.add(lblCadastrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        btnCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar.png"))); // NOI18N
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlSecundario.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 220, 50));

        lblTextoCadastrar1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTextoCadastrar1.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoCadastrar1.setText("Opa! Ainda não tem uma conta?");
        lblTextoCadastrar1.setToolTipText("");
        pnlSecundario.add(lblTextoCadastrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 370, 30));

        lblTextoCadastrar2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTextoCadastrar2.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoCadastrar2.setText("Clique no botão abaixo e crie");
        lblTextoCadastrar2.setToolTipText("");
        pnlSecundario.add(lblTextoCadastrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 326, 340, 40));

        lblTextoCadastrar3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTextoCadastrar3.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoCadastrar3.setText("a sua agora mesmo.");
        lblTextoCadastrar3.setToolTipText("");
        pnlSecundario.add(lblTextoCadastrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 240, 40));

        iconCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perfilCadastrar.png"))); // NOI18N
        pnlSecundario.add(iconCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        pnlPrincipal.add(pnlSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 640, 720));

        lblSenha.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblSenha.setText("Senha");
        pnlPrincipal.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        lblLogar1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lblLogar1.setForeground(new java.awt.Color(0, 0, 0));
        lblLogar1.setText("LOGAR");
        pnlPrincipal.add(lblLogar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        lblEmail1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblEmail1.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail1.setText("E-Mail");
        pnlPrincipal.add(lblEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        edtSenha.setBackground(new java.awt.Color(251, 186, 0));
        edtSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtSenhaActionPerformed(evt);
            }
        });
        edtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtSenhaKeyPressed(evt);
            }
        });
        pnlPrincipal.add(edtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 480, 50));
        edtSenha.getAccessibleContext().setAccessibleName("");

        edtEmail.setBackground(new java.awt.Color(251, 186, 0));
        edtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEmail.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEmail.setPreferredSize(new java.awt.Dimension(10, 20));
        edtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEmailActionPerformed(evt);
            }
        });
        pnlPrincipal.add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 480, 50));

        btnLogar1.setBackground(new java.awt.Color(251, 186, 0));
        btnLogar1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnLogar1.setForeground(new java.awt.Color(0, 0, 0));
        btnLogar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chave.png"))); // NOI18N
        btnLogar1.setText("LOGAR");
        btnLogar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnLogar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogar1ActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnLogar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 150, 50));

        iconLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/perfilLogar.png"))); // NOI18N
        pnlPrincipal.add(iconLogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        getContentPane().add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtSenhaActionPerformed

    private void edtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmailActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(Util.getIcone());
    }//GEN-LAST:event_formWindowOpened

    private void btnLogar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogar1ActionPerformed

    private void edtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
        }
    }//GEN-LAST:event_edtSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLogar1;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtSenha;
    private javax.swing.JLabel iconCadastrar;
    private javax.swing.JLabel iconLogar;
    private javax.swing.JLabel lblCadastrar1;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblLogar1;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTextoCadastrar1;
    private javax.swing.JLabel lblTextoCadastrar2;
    private javax.swing.JLabel lblTextoCadastrar3;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSecundario;
    // End of variables declaration//GEN-END:variables
}
