/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

/**
 *
 * @author eleaa
 */
public class FrMenuInstrutor extends javax.swing.JFrame {

    /**
     * Creates new form FrMenuInstrutor
     */
    public FrMenuInstrutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlSecundario = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        btnCriarTreino = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnConsultarTreinos = new javax.swing.JButton();
        btnEditarPerfil = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSecundario.setBackground(new java.awt.Color(251, 80, 0));
        pnlSecundario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setBackground(new java.awt.Color(255, 102, 102));
        btnLogout.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 0));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icone sair.png"))); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 300, 60));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoMenor.png"))); // NOI18N
        pnlSecundario.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        btnCriarTreino.setBackground(new java.awt.Color(255, 255, 255));
        btnCriarTreino.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnCriarTreino.setForeground(new java.awt.Color(0, 0, 0));
        btnCriarTreino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeTreinos.png"))); // NOI18N
        btnCriarTreino.setText("CRIAR TREINO");
        btnCriarTreino.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCriarTreino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCriarTreinoMouseClicked(evt);
            }
        });
        btnCriarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarTreinoActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnCriarTreino, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 360, 60));

        btnClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnClientes.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icone Saude.png"))); // NOI18N
        btnClientes.setText("CLIENTES");
        btnClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 300, 60));

        btnConsultarTreinos.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultarTreinos.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnConsultarTreinos.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultarTreinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icone avaliacao fisica.png"))); // NOI18N
        btnConsultarTreinos.setText("CONSULTAR TREINOS");
        btnConsultarTreinos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnConsultarTreinos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultarTreinosMouseClicked(evt);
            }
        });
        btnConsultarTreinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarTreinosActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnConsultarTreinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 360, 60));

        btnEditarPerfil.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarPerfil.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnEditarPerfil.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icone Planos.png"))); // NOI18N
        btnEditarPerfil.setText("EDITAR PERFIL");
        btnEditarPerfil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnEditarPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarPerfilMouseClicked(evt);
            }
        });
        btnEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerfilActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 300, 60));

        pnlPrincipal.add(pnlSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 170));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/academia.png"))); // NOI18N
        background.setText("jLabel1");
        pnlPrincipal.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        new FrLogarInstrutor().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCriarTreinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCriarTreinoMouseClicked
         new FrCriarTreino().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnCriarTreinoMouseClicked

    private void btnCriarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarTreinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCriarTreinoActionPerformed

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        new FrSaude().setVisible(true);
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnConsultarTreinosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarTreinosMouseClicked
        new FrConsultarTreinos().setVisible(true);
    }//GEN-LAST:event_btnConsultarTreinosMouseClicked

    private void btnConsultarTreinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarTreinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarTreinosActionPerformed

    private void btnEditarPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarPerfilMouseClicked
        new FrPlanos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditarPerfilMouseClicked

    private void btnEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenuInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenuInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenuInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenuInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenuInstrutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnConsultarTreinos;
    private javax.swing.JButton btnCriarTreino;
    private javax.swing.JButton btnEditarPerfil;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSecundario;
    // End of variables declaration//GEN-END:variables
}
