/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

/**
 *
 * @author aluno.saolucas
 */
public class FrMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     */
    public FrMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlSecundario = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        btnTreinos = new javax.swing.JButton();
        btnSaude = new javax.swing.JButton();
        btnAvaliacao = new javax.swing.JButton();
        btnPlanos = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Menu - FitZone");

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSecundario.setBackground(new java.awt.Color(251, 186, 0));
        pnlSecundario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSair.setBackground(new java.awt.Color(255, 102, 102));
        btnSair.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnSair.setForeground(new java.awt.Color(0, 0, 0));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icone sair.png"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, 240, 60));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoMenor.png"))); // NOI18N
        pnlSecundario.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        btnTreinos.setBackground(new java.awt.Color(255, 255, 255));
        btnTreinos.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnTreinos.setForeground(new java.awt.Color(0, 0, 0));
        btnTreinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeTreinos.png"))); // NOI18N
        btnTreinos.setText("TREINOS");
        btnTreinos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnTreinos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTreinosMouseClicked(evt);
            }
        });
        btnTreinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreinosActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnTreinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 240, 60));

        btnSaude.setBackground(new java.awt.Color(255, 255, 255));
        btnSaude.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnSaude.setForeground(new java.awt.Color(0, 0, 0));
        btnSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icone Saude.png"))); // NOI18N
        btnSaude.setText("SAÚDE");
        btnSaude.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSaude.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaudeMouseClicked(evt);
            }
        });
        btnSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaudeActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnSaude, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 240, 60));

        btnAvaliacao.setBackground(new java.awt.Color(255, 255, 255));
        btnAvaliacao.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnAvaliacao.setForeground(new java.awt.Color(0, 0, 0));
        btnAvaliacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icone avaliacao fisica.png"))); // NOI18N
        btnAvaliacao.setText("AVALIAÇÃO");
        btnAvaliacao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnAvaliacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAvaliacaoMouseClicked(evt);
            }
        });
        btnAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliacaoActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnAvaliacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 240, 60));

        btnPlanos.setBackground(new java.awt.Color(255, 255, 255));
        btnPlanos.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnPlanos.setForeground(new java.awt.Color(0, 0, 0));
        btnPlanos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icone Planos.png"))); // NOI18N
        btnPlanos.setText("PLANOS");
        btnPlanos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnPlanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlanosMouseClicked(evt);
            }
        });
        btnPlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanosActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnPlanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 240, 60));

        btnPerfil.setBackground(new java.awt.Color(255, 255, 255));
        btnPerfil.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(0, 0, 0));
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icone perfil.png"))); // NOI18N
        btnPerfil.setText("PERFIL");
        btnPerfil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
        });
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 240, 60));

        pnlPrincipal.add(pnlSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 170));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/academia.png"))); // NOI18N
        background.setText("jLabel1");
        pnlPrincipal.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 810));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
       
    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnTreinosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTreinosMouseClicked
       new FrMenu().setVisible(true);
    }//GEN-LAST:event_btnTreinosMouseClicked

    private void btnTreinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTreinosActionPerformed

    private void btnSaudeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaudeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaudeMouseClicked

    private void btnSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaudeActionPerformed

    private void btnAvaliacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvaliacaoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAvaliacaoMouseClicked

    private void btnAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAvaliacaoActionPerformed

    private void btnPlanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlanosMouseClicked

    private void btnPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlanosActionPerformed

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfilMouseClicked

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel background;
    private javax.swing.JButton btnAvaliacao;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnPlanos;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSaude;
    private javax.swing.JButton btnTreinos;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSecundario;
    // End of variables declaration//GEN-END:variables
}
