/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controlar.ControladorDeUsuario;
import java.awt.Color;
import java.io.File;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import modelo.Usuario;
import modelo.UsuarioLogado;
import utilidade.Util;

/**
 *
 * @author eleaa
 */
public class FrPerfil extends javax.swing.JFrame {

    private Usuario usuarioAtual = UsuarioLogado.getUsuarioLogado();

    /**
     * Creates new form FrPerfil
     */
    public FrPerfil() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlSecundario = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        btnEscolherImagem = new javax.swing.JButton();
        pnlFoto = new javax.swing.JPanel();
        imgFoto = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblConfirmarSenha = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        edtObjetivo = new javax.swing.JTextField();
        lblObjetivo = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        edtTelefone = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnAlterarSenha = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        edtDataNascimento = new javax.swing.JFormattedTextField();
        edtCpf = new javax.swing.JFormattedTextField();
        edtConfirmarSenha = new javax.swing.JPasswordField();
        edtSenha = new javax.swing.JPasswordField();
        lblLogo = new javax.swing.JLabel();
        lblAlterarPerfil = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSecundario.setBackground(new java.awt.Color(255, 255, 255));
        pnlSecundario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblNome.setForeground(new java.awt.Color(251, 186, 0));
        lblNome.setText("Nome");
        pnlSecundario.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        edtNome.setBackground(new java.awt.Color(251, 186, 0));
        edtNome.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtNome.setForeground(new java.awt.Color(0, 0, 0));
        edtNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtNome.setMinimumSize(new java.awt.Dimension(10, 20));
        edtNome.setPreferredSize(new java.awt.Dimension(10, 20));
        pnlSecundario.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 510, 30));

        btnEscolherImagem.setBackground(new java.awt.Color(255, 153, 153));
        btnEscolherImagem.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnEscolherImagem.setForeground(new java.awt.Color(0, 0, 0));
        btnEscolherImagem.setText("ESCOLHER IMAGEM");
        btnEscolherImagem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnEscolherImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEscolherImagemMouseClicked(evt);
            }
        });
        btnEscolherImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolherImagemActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnEscolherImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 160, 50));

        pnlFoto.setBackground(new java.awt.Color(255, 255, 255));
        pnlFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlFotoLayout = new javax.swing.GroupLayout(pnlFoto);
        pnlFoto.setLayout(pnlFotoLayout);
        pnlFotoLayout.setHorizontalGroup(
            pnlFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoLayout.createSequentialGroup()
                .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlFotoLayout.setVerticalGroup(
            pnlFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoLayout.createSequentialGroup()
                .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlSecundario.add(pnlFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 100, 133));

        edtEmail.setBackground(new java.awt.Color(251, 186, 0));
        edtEmail.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtEmail.setForeground(new java.awt.Color(0, 0, 0));
        edtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEmail.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEmail.setPreferredSize(new java.awt.Dimension(10, 20));
        pnlSecundario.add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 510, 30));

        lblEmail.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(251, 186, 0));
        lblEmail.setText("E-Mail");
        pnlSecundario.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        lblConfirmarSenha.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblConfirmarSenha.setForeground(new java.awt.Color(251, 186, 0));
        lblConfirmarSenha.setText("Repetir Senha");
        pnlSecundario.add(lblConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        lblSenha.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(251, 186, 0));
        lblSenha.setText("Senha");
        pnlSecundario.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 30));

        edtObjetivo.setBackground(new java.awt.Color(251, 186, 0));
        edtObjetivo.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtObjetivo.setForeground(new java.awt.Color(0, 0, 0));
        edtObjetivo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtObjetivo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtObjetivo.setMinimumSize(new java.awt.Dimension(10, 20));
        edtObjetivo.setPreferredSize(new java.awt.Dimension(10, 20));
        pnlSecundario.add(edtObjetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 240, 30));

        lblObjetivo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblObjetivo.setForeground(new java.awt.Color(251, 186, 0));
        lblObjetivo.setText("Objetivo");
        pnlSecundario.add(lblObjetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 30));

        lblDataNascimento.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblDataNascimento.setForeground(new java.awt.Color(251, 186, 0));
        lblDataNascimento.setText("Data de nascimento");
        pnlSecundario.add(lblDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 30));

        lblCpf.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(251, 186, 0));
        lblCpf.setText("CPF");
        pnlSecundario.add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, 30));

        edtTelefone.setBackground(new java.awt.Color(251, 186, 0));
        edtTelefone.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtTelefone.setForeground(new java.awt.Color(0, 0, 0));
        edtTelefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtTelefone.setMinimumSize(new java.awt.Dimension(10, 20));
        edtTelefone.setPreferredSize(new java.awt.Dimension(10, 20));
        pnlSecundario.add(edtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 240, 30));

        lblTelefone.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(251, 186, 0));
        lblTelefone.setText("Telefone");
        pnlSecundario.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, 30));

        btnAlterar.setBackground(new java.awt.Color(102, 255, 102));
        btnAlterar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnAlterar.setForeground(new java.awt.Color(0, 0, 0));
        btnAlterar.setText("ALTERAR");
        btnAlterar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 100, 40));

        btnAlterarSenha.setBackground(new java.awt.Color(251, 186, 0));
        btnAlterarSenha.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnAlterarSenha.setForeground(new java.awt.Color(0, 0, 0));
        btnAlterarSenha.setText("ALTERAR SENHA");
        btnAlterarSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnAlterarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarSenhaMouseClicked(evt);
            }
        });
        btnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSenhaActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnAlterarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 180, 40));

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlSecundario.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 110, 40));

        edtDataNascimento.setBackground(new java.awt.Color(251, 186, 0));
        edtDataNascimento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        edtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDataNascimentoActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 240, 30));

        edtCpf.setBackground(new java.awt.Color(251, 186, 0));
        edtCpf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        try {
            edtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###,###,###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        edtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCpfActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 240, 30));

        edtConfirmarSenha.setBackground(new java.awt.Color(251, 186, 0));
        edtConfirmarSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtConfirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtConfirmarSenhaActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 510, 30));

        edtSenha.setBackground(new java.awt.Color(251, 186, 0));
        edtSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtSenhaActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 510, 30));

        jPanel1.add(pnlSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 840, 530));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoMenor.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 130));

        lblAlterarPerfil.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lblAlterarPerfil.setForeground(new java.awt.Color(251, 186, 0));
        lblAlterarPerfil.setText("ALTERAR PERFIL");
        jPanel1.add(lblAlterarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background Saude.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 1290, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscolherImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscolherImagemMouseClicked
        escolherImagem();
    }//GEN-LAST:event_btnEscolherImagemMouseClicked

    private void btnEscolherImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolherImagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEscolherImagemActionPerformed

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        salvarPerfil();
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnAlterarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarSenhaMouseClicked
        if (edtSenha.isEditable()) {
            edtSenha.setEditable(false);
            edtConfirmarSenha.setEditable(false);
            edtSenha.setBackground(new Color(145, 109, 7));
            edtConfirmarSenha.setBackground(new Color(145, 109, 7));

            edtSenha.setText("");
            edtConfirmarSenha.setText("");

            btnAlterarSenha.setText("Alterar Senha");
        } else {
            edtSenha.setEditable(true);
            edtConfirmarSenha.setEditable(true);
            edtSenha.setBackground(new Color(251, 186, 0));
            edtConfirmarSenha.setBackground(new Color(251, 186, 0));

            btnAlterarSenha.setText("Cancelar");
        }
    }//GEN-LAST:event_btnAlterarSenhaMouseClicked

    private void btnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarSenhaActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        new FrMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void edtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDataNascimentoActionPerformed

    private void edtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCpfActionPerformed

    private void edtConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtConfirmarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtConfirmarSenhaActionPerformed

    private void edtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtSenhaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(Util.getIcone());
        Usuario usuario = UsuarioLogado.getUsuarioLogado();

        edtNome.setText(usuario.getNome());
        edtEmail.setText(usuario.getEmail());
        edtTelefone.setText(usuario.getTelefone());
        edtDataNascimento.setText(Util.converterDateToString(usuario.getDataNascimento()));
        edtObjetivo.setText(usuario.getObjetivo());
        edtCpf.setText(usuario.getCpf());;
        imgFoto.setIcon(usuario.getImagem());
        Icon icone = usuario.getImagem();
        if (icone != null) {
            Icon iconeRed = Util.redimensionarImagem(icone, 96, 129);
            imgFoto.setIcon(iconeRed);
        }

    }//GEN-LAST:event_formWindowOpened

    private void escolherImagem() {
        File arquivo = Util.escolherImagem();
        if (arquivo != null) {
            Icon icone = Util.converterFileToIcon(arquivo);
            Icon iconeNovo = Util.redimensionarImagem(icone, 96, 129);
            imgFoto.setIcon(iconeNovo);
            // guardar no objeto
            usuarioAtual.setImagem(iconeNovo);
        }
    }

    private void salvarPerfil() {
        // verificar campos se quiser

        usuarioAtual.setNome(edtNome.getText());
        usuarioAtual.setEmail(edtEmail.getText());
        String s = new String(edtSenha.getPassword());
        if (!s.isEmpty()) {
            usuarioAtual.setSenha(Util.calcularHash(s));
        }
        usuarioAtual.setTelefone(edtTelefone.getText());
        usuarioAtual.setDataNascimento(Util.converterStringToDate(edtDataNascimento.getText()));
        usuarioAtual.setObjetivo(edtObjetivo.getText());
        usuarioAtual.setCpf(usuarioAtual.removerCpf(edtCpf.getText()));

        // imagem já foi setada no escolherImagem
        ControladorDeUsuario ctrl = new ControladorDeUsuario();
        boolean ok = ctrl.alterar(usuarioAtual);
        if (ok) {
            JOptionPane.showMessageDialog(this, "Perfil atualizado com sucesso!");
            // opcional: atualizar UsuarioLogado
            UsuarioLogado.setUsuarioLogado(usuarioAtual);
        } else {
            JOptionPane.showMessageDialog(this, "Falha ao atualizar o perfil.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrPerfil.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrPerfil.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrPerfil.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrPerfil.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEscolherImagem;
    private javax.swing.JPasswordField edtConfirmarSenha;
    private javax.swing.JFormattedTextField edtCpf;
    private javax.swing.JFormattedTextField edtDataNascimento;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtObjetivo;
    private javax.swing.JPasswordField edtSenha;
    private javax.swing.JTextField edtTelefone;
    private javax.swing.JLabel imgFoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlterarPerfil;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObjetivo;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel pnlFoto;
    private javax.swing.JPanel pnlSecundario;
    // End of variables declaration//GEN-END:variables
}
