/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

/**
 *
 * @author eleaa
 */
public class FrPerfil extends javax.swing.JFrame {

    /**
     * Creates new form FrPerfil
     */
    public FrPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        edtEmail11 = new javax.swing.JTextField();
        btnEscolherImagem = new javax.swing.JButton();
        pnlFoto = new javax.swing.JPanel();
        imgFoto1 = new javax.swing.JLabel();
        edtEmail12 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        edtEmail15 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        edtEmail18 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnSair4 = new javax.swing.JButton();
        btnSair5 = new javax.swing.JButton();
        btnSair6 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        lblLogo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSair2 = new javax.swing.JButton();
        btnSair3 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(251, 186, 0));
        jLabel10.setText("Nome");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        edtEmail11.setBackground(new java.awt.Color(251, 186, 0));
        edtEmail11.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtEmail11.setForeground(new java.awt.Color(0, 0, 0));
        edtEmail11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEmail11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEmail11.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEmail11.setPreferredSize(new java.awt.Dimension(10, 20));
        jPanel2.add(edtEmail11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 510, 30));

        btnEscolherImagem.setBackground(new java.awt.Color(255, 153, 153));
        btnEscolherImagem.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnEscolherImagem.setForeground(new java.awt.Color(0, 0, 0));
        btnEscolherImagem.setText("ESCOLHER IMAGEM");
        btnEscolherImagem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnEscolherImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEscolherImagemMouseClicked(evt);
            }
        });
        btnEscolherImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolherImagemActionPerformed(evt);
            }
        });
        jPanel2.add(btnEscolherImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 160, 50));

        pnlFoto.setBackground(new java.awt.Color(255, 255, 255));
        pnlFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlFotoLayout = new javax.swing.GroupLayout(pnlFoto);
        pnlFoto.setLayout(pnlFotoLayout);
        pnlFotoLayout.setHorizontalGroup(
            pnlFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoLayout.createSequentialGroup()
                .addComponent(imgFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlFotoLayout.setVerticalGroup(
            pnlFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoLayout.createSequentialGroup()
                .addComponent(imgFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(pnlFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 100, 133));

        edtEmail12.setBackground(new java.awt.Color(251, 186, 0));
        edtEmail12.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtEmail12.setForeground(new java.awt.Color(0, 0, 0));
        edtEmail12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEmail12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEmail12.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEmail12.setPreferredSize(new java.awt.Dimension(10, 20));
        jPanel2.add(edtEmail12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 510, 30));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(251, 186, 0));
        jLabel11.setText("E-Mail");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(251, 186, 0));
        jLabel12.setText("Repetir Senha");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(251, 186, 0));
        jLabel13.setText("Senha");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, 30));

        edtEmail15.setBackground(new java.awt.Color(251, 186, 0));
        edtEmail15.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtEmail15.setForeground(new java.awt.Color(0, 0, 0));
        edtEmail15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEmail15.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEmail15.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEmail15.setPreferredSize(new java.awt.Dimension(10, 20));
        jPanel2.add(edtEmail15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 240, 30));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(251, 186, 0));
        jLabel14.setText("Objetivo");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 30));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(251, 186, 0));
        jLabel15.setText("Data de nascimento");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, 30));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(251, 186, 0));
        jLabel16.setText("CPF");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, 30));

        edtEmail18.setBackground(new java.awt.Color(251, 186, 0));
        edtEmail18.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtEmail18.setForeground(new java.awt.Color(0, 0, 0));
        edtEmail18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEmail18.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEmail18.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEmail18.setPreferredSize(new java.awt.Dimension(10, 20));
        jPanel2.add(edtEmail18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 240, 30));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(251, 186, 0));
        jLabel17.setText("Telefone");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, 30));

        btnSair4.setBackground(new java.awt.Color(102, 255, 102));
        btnSair4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnSair4.setForeground(new java.awt.Color(0, 0, 0));
        btnSair4.setText("ALTERAR");
        btnSair4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSair4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSair4MouseClicked(evt);
            }
        });
        btnSair4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSair4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 100, 40));

        btnSair5.setBackground(new java.awt.Color(251, 186, 0));
        btnSair5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnSair5.setForeground(new java.awt.Color(0, 0, 0));
        btnSair5.setText("ALTERAR SENHA");
        btnSair5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSair5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSair5MouseClicked(evt);
            }
        });
        btnSair5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair5ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSair5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 180, 40));

        btnSair6.setBackground(new java.awt.Color(255, 102, 102));
        btnSair6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        btnSair6.setForeground(new java.awt.Color(0, 0, 0));
        btnSair6.setText("CANCELAR");
        btnSair6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSair6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSair6MouseClicked(evt);
            }
        });
        btnSair6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair6ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSair6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 110, 40));

        jFormattedTextField1.setBackground(new java.awt.Color(251, 186, 0));
        jFormattedTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 240, 30));

        jFormattedTextField2.setBackground(new java.awt.Color(251, 186, 0));
        jFormattedTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###,###,###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 240, 30));

        jPasswordField1.setBackground(new java.awt.Color(251, 186, 0));
        jPasswordField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 510, 30));

        jPasswordField2.setBackground(new java.awt.Color(251, 186, 0));
        jPasswordField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 510, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 840, 530));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoMenor.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 130));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(251, 186, 0));
        jLabel3.setText("ALTERAR PERFIL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        btnSair2.setBackground(new java.awt.Color(255, 102, 102));
        btnSair2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnSair2.setForeground(new java.awt.Color(0, 0, 0));
        btnSair2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icone sair.png"))); // NOI18N
        btnSair2.setText("VOLTAR");
        btnSair2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSair2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSair2MouseClicked(evt);
            }
        });
        btnSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 180, 60));

        btnSair3.setBackground(new java.awt.Color(255, 102, 102));
        btnSair3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnSair3.setForeground(new java.awt.Color(0, 0, 0));
        btnSair3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icone sair.png"))); // NOI18N
        btnSair3.setText("SAIR");
        btnSair3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSair3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSair3MouseClicked(evt);
            }
        });
        btnSair3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 140, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background Saude.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 1290, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscolherImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEscolherImagemMouseClicked

        File arquivo = Util.escolherImagem();

        if(arquivo != null){
            Icon icone = Util.converterFileToIcon(arquivo);

            Icon iconeNovo = Util.redimensionarImagem(icone, 96, 129);

            imgFoto.setIcon(iconeNovo);
        }
    }//GEN-LAST:event_btnEscolherImagemMouseClicked

    private void btnEscolherImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolherImagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEscolherImagemActionPerformed

    private void btnSair2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSair2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSair2MouseClicked

    private void btnSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSair2ActionPerformed

    private void btnSair3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSair3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSair3MouseClicked

    private void btnSair3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSair3ActionPerformed

    private void btnSair4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSair4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSair4MouseClicked

    private void btnSair4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSair4ActionPerformed

    private void btnSair5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSair5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSair5MouseClicked

    private void btnSair5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSair5ActionPerformed

    private void btnSair6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSair6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSair6MouseClicked

    private void btnSair6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSair6ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnEscolherImagem;
    private javax.swing.JButton btnSair2;
    private javax.swing.JButton btnSair3;
    private javax.swing.JButton btnSair4;
    private javax.swing.JButton btnSair5;
    private javax.swing.JButton btnSair6;
    private javax.swing.JTextField edtEmail11;
    private javax.swing.JTextField edtEmail12;
    private javax.swing.JTextField edtEmail15;
    private javax.swing.JTextField edtEmail18;
    private javax.swing.JLabel imgFoto1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlFoto;
    // End of variables declaration//GEN-END:variables
}
