/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controlar.ControladorDeAvaliacao;
import controlar.ControladorDeDieta;
import java.util.List;
import modelo.AvaliacaoFisica;
import modelo.UsuarioLogado;
import utilidade.Util;

import javax.swing.JOptionPane;

/**
 *
 * @author eleaa
 */
public class FrSaude extends javax.swing.JFrame {

    /**
     * Creates new form FrSas
     */
    public FrSaude() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPerder = new javax.swing.JButton();
        btnManter = new javax.swing.JButton();
        btnGanhar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblLogo2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblLogo1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTmb = new javax.swing.JLabel();
        edtAltura = new javax.swing.JTextField();
        edtPeso = new javax.swing.JTextField();
        edtGorduraCorporal = new javax.swing.JTextField();
        edtMassaMuscular = new javax.swing.JTextField();
        edtImc = new javax.swing.JTextField();
        edtTmb = new javax.swing.JTextField();
        lblInformacoesPessoais = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblMassaMuscular = new javax.swing.JLabel();
        lblGorduraCorporal = new javax.swing.JLabel();
        lblImc = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnRemoverDieta = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FitZone - Saúde - Usuário");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPerder.setBackground(new java.awt.Color(251, 186, 0));
        btnPerder.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnPerder.setForeground(new java.awt.Color(0, 0, 0));
        btnPerder.setText("Perder Peso");
        btnPerder.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnPerder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerderMouseClicked(evt);
            }
        });
        btnPerder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerderActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerder, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 260, 240, 60));

        btnManter.setBackground(new java.awt.Color(251, 186, 0));
        btnManter.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnManter.setForeground(new java.awt.Color(0, 0, 0));
        btnManter.setText("Manter Peso");
        btnManter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnManter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManterMouseClicked(evt);
            }
        });
        btnManter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManterActionPerformed(evt);
            }
        });
        jPanel1.add(btnManter, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 420, 240, 60));

        btnGanhar.setBackground(new java.awt.Color(251, 186, 0));
        btnGanhar.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnGanhar.setForeground(new java.awt.Color(0, 0, 0));
        btnGanhar.setText("Ganhar Peso");
        btnGanhar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnGanhar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGanharMouseClicked(evt);
            }
        });
        btnGanhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGanharActionPerformed(evt);
            }
        });
        jPanel1.add(btnGanhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 580, 240, 60));

        jPanel2.setBackground(new java.awt.Color(251, 186, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/output-onlinepngtools (1).png"))); // NOI18N
        jPanel6.add(lblLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 200, 140));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 186, 0));
        jLabel2.setText("Saúde");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 7, -1, 130));

        btnSair.setBackground(new java.awt.Color(255, 0, 0));
        btnSair.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnSair.setForeground(new java.awt.Color(0, 0, 0));
        btnSair.setText("Sair");
        btnSair.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel6.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 50, 90, 60));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 140));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 145));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/output-onlinepngtools (1).png"))); // NOI18N
        jPanel5.add(lblLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 200, 140));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(251, 186, 0));
        jLabel3.setText("Planos");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, 140));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 140));

        lblTmb.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTmb.setForeground(new java.awt.Color(251, 186, 0));
        lblTmb.setText("TMB(Taxa metabólica basal)");
        jPanel1.add(lblTmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, -1));

        edtAltura.setEditable(false);
        edtAltura.setBackground(new java.awt.Color(251, 186, 0));
        edtAltura.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        edtAltura.setForeground(new java.awt.Color(0, 0, 0));
        edtAltura.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtAltura.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtAltura.setMinimumSize(new java.awt.Dimension(10, 20));
        edtAltura.setPreferredSize(new java.awt.Dimension(10, 20));
        edtAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtAlturaActionPerformed(evt);
            }
        });
        jPanel1.add(edtAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 240, 30));

        edtPeso.setEditable(false);
        edtPeso.setBackground(new java.awt.Color(251, 186, 0));
        edtPeso.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        edtPeso.setForeground(new java.awt.Color(0, 0, 0));
        edtPeso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtPeso.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtPeso.setMinimumSize(new java.awt.Dimension(10, 20));
        edtPeso.setPreferredSize(new java.awt.Dimension(10, 20));
        edtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtPesoActionPerformed(evt);
            }
        });
        jPanel1.add(edtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 240, 30));

        edtGorduraCorporal.setEditable(false);
        edtGorduraCorporal.setBackground(new java.awt.Color(251, 186, 0));
        edtGorduraCorporal.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        edtGorduraCorporal.setForeground(new java.awt.Color(0, 0, 0));
        edtGorduraCorporal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtGorduraCorporal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtGorduraCorporal.setMinimumSize(new java.awt.Dimension(10, 20));
        edtGorduraCorporal.setPreferredSize(new java.awt.Dimension(10, 20));
        edtGorduraCorporal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtGorduraCorporalActionPerformed(evt);
            }
        });
        jPanel1.add(edtGorduraCorporal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 240, 30));

        edtMassaMuscular.setEditable(false);
        edtMassaMuscular.setBackground(new java.awt.Color(251, 186, 0));
        edtMassaMuscular.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        edtMassaMuscular.setForeground(new java.awt.Color(0, 0, 0));
        edtMassaMuscular.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtMassaMuscular.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtMassaMuscular.setMinimumSize(new java.awt.Dimension(10, 20));
        edtMassaMuscular.setPreferredSize(new java.awt.Dimension(10, 20));
        edtMassaMuscular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtMassaMuscularActionPerformed(evt);
            }
        });
        jPanel1.add(edtMassaMuscular, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 240, 30));

        edtImc.setEditable(false);
        edtImc.setBackground(new java.awt.Color(251, 186, 0));
        edtImc.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        edtImc.setForeground(new java.awt.Color(0, 0, 0));
        edtImc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtImc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtImc.setMinimumSize(new java.awt.Dimension(10, 20));
        edtImc.setPreferredSize(new java.awt.Dimension(10, 20));
        edtImc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtImcActionPerformed(evt);
            }
        });
        jPanel1.add(edtImc, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 240, 30));

        edtTmb.setEditable(false);
        edtTmb.setBackground(new java.awt.Color(251, 186, 0));
        edtTmb.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        edtTmb.setForeground(new java.awt.Color(0, 0, 0));
        edtTmb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtTmb.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtTmb.setMinimumSize(new java.awt.Dimension(10, 20));
        edtTmb.setPreferredSize(new java.awt.Dimension(10, 20));
        edtTmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTmbActionPerformed(evt);
            }
        });
        jPanel1.add(edtTmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 240, 30));

        lblInformacoesPessoais.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblInformacoesPessoais.setForeground(new java.awt.Color(251, 186, 0));
        lblInformacoesPessoais.setText("Informacoes pessoais:");
        jPanel1.add(lblInformacoesPessoais, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        lblPeso.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblPeso.setForeground(new java.awt.Color(251, 186, 0));
        lblPeso.setText("Peso");
        jPanel1.add(lblPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

        lblAltura.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblAltura.setForeground(new java.awt.Color(251, 186, 0));
        lblAltura.setText("Altura");
        jPanel1.add(lblAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        lblMassaMuscular.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblMassaMuscular.setForeground(new java.awt.Color(251, 186, 0));
        lblMassaMuscular.setText("Massa Muscular");
        jPanel1.add(lblMassaMuscular, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        lblGorduraCorporal.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblGorduraCorporal.setForeground(new java.awt.Color(251, 186, 0));
        lblGorduraCorporal.setText("Gordura Corporal");
        jPanel1.add(lblGorduraCorporal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        lblImc.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblImc.setForeground(new java.awt.Color(251, 186, 0));
        lblImc.setText("IMC(Índice de massa corporal)");
        jPanel1.add(lblImc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));

        btnCalcular.setBackground(new java.awt.Color(251, 186, 0));
        btnCalcular.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcular.setText("Calcular");
        btnCalcular.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularMouseClicked(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 580, 220, 60));

        btnRemoverDieta.setBackground(new java.awt.Color(251, 186, 0));
        btnRemoverDieta.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnRemoverDieta.setForeground(new java.awt.Color(0, 0, 0));
        btnRemoverDieta.setText("Remover Dieta Atual");
        btnRemoverDieta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnRemoverDieta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoverDietaMouseClicked(evt);
            }
        });
        btnRemoverDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverDietaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemoverDieta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 380, 60));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Background.png"))); // NOI18N
        Background.setText("jLabel1");
        Background.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setIconImage(Util.getIcone());
        ControladorDeAvaliacao conAva = new ControladorDeAvaliacao();
        List<AvaliacaoFisica> listaAva = conAva.consultar(UsuarioLogado.getUsuarioLogado().getPkUsuario());
        AvaliacaoFisica ava = listaAva.get(0);
        edtPeso.setText(String.valueOf(ava.getPeso()));
        edtAltura.setText(String.valueOf(ava.getAltura()));
    }//GEN-LAST:event_formWindowOpened

    private void btnGanharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGanharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGanharActionPerformed

    private void btnGanharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGanharMouseClicked
        new FrGanharPeso().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGanharMouseClicked

    private void btnManterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManterActionPerformed

    private void btnManterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManterMouseClicked
        new FrManterPeso().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManterMouseClicked

    private void btnPerderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPerderActionPerformed

    private void btnPerderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerderMouseClicked
        new FrPerderPeso().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPerderMouseClicked

    private void btnRemoverDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverDietaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoverDietaActionPerformed

    private void btnRemoverDietaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverDietaMouseClicked
        Remover();
    }//GEN-LAST:event_btnRemoverDietaMouseClicked

    private void btnCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseClicked
        calcular();
    }//GEN-LAST:event_btnCalcularMouseClicked

    private void edtTmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTmbActionPerformed

    private void edtImcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtImcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtImcActionPerformed

    private void edtMassaMuscularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtMassaMuscularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtMassaMuscularActionPerformed

    private void edtGorduraCorporalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtGorduraCorporalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtGorduraCorporalActionPerformed

    private void edtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtPesoActionPerformed

    private void edtAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtAlturaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        new FrMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairMouseClicked

    private void calcular() {
        ControladorDeAvaliacao conAva = new ControladorDeAvaliacao();
        List<AvaliacaoFisica> listaAva = conAva.consultar(UsuarioLogado.getUsuarioLogado().getPkUsuario());
        AvaliacaoFisica ava = listaAva.get(0);
        edtMassaMuscular.setText(String.valueOf(ava.getMassa_muscular()) + "%");
        edtGorduraCorporal.setText(String.valueOf(ava.getGordura_corporal()) + "%");
        edtImc.setText(String.valueOf(ava.getImc()));
        edtTmb.setText(String.valueOf(ava.getTmb()));
    }

    private void Remover() {
        ControladorDeDieta conDie = new ControladorDeDieta();
        if (conDie.remover(UsuarioLogado.getUsuarioLogado().getPkUsuario())) {
            JOptionPane.showMessageDialog(this, "Dieta removida com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao remover a dieta.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrSaude().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnGanhar;
    private javax.swing.JButton btnManter;
    private javax.swing.JButton btnPerder;
    private javax.swing.JButton btnRemoverDieta;
    private javax.swing.JButton btnSair;
    private javax.swing.JTextField edtAltura;
    private javax.swing.JTextField edtGorduraCorporal;
    private javax.swing.JTextField edtImc;
    private javax.swing.JTextField edtMassaMuscular;
    private javax.swing.JTextField edtPeso;
    private javax.swing.JTextField edtTmb;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblGorduraCorporal;
    private javax.swing.JLabel lblImc;
    private javax.swing.JLabel lblInformacoesPessoais;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblLogo2;
    private javax.swing.JLabel lblMassaMuscular;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblTmb;
    // End of variables declaration//GEN-END:variables
}
