/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

/**
 *
 * @author eleaa
 */
public class FrSaude extends javax.swing.JFrame {

    /**
     * Creates new form FrSas
     */
    public FrSaude() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();
        pnlSecundario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        edtEmail1 = new javax.swing.JTextField();
        edtEmail2 = new javax.swing.JTextField();
        edtEmail3 = new javax.swing.JTextField();
        edtEmail4 = new javax.swing.JTextField();
        edtEmail5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        btnTreinos = new javax.swing.JButton();
        btnTreinos1 = new javax.swing.JButton();
        btnTreinos2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSecundario.setBackground(new java.awt.Color(255, 255, 255));
        pnlSecundario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlSecundario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(251, 186, 0));
        jLabel1.setText("TMB(Taxa metabolica basal)");
        pnlSecundario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        edtEmail.setBackground(new java.awt.Color(251, 186, 0));
        edtEmail.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtEmail.setForeground(new java.awt.Color(0, 0, 0));
        edtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEmail.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEmail.setPreferredSize(new java.awt.Dimension(10, 20));
        edtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEmailActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 240, 30));

        edtEmail1.setBackground(new java.awt.Color(251, 186, 0));
        edtEmail1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtEmail1.setForeground(new java.awt.Color(0, 0, 0));
        edtEmail1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEmail1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEmail1.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEmail1.setPreferredSize(new java.awt.Dimension(10, 20));
        edtEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEmail1ActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 240, 30));

        edtEmail2.setBackground(new java.awt.Color(251, 186, 0));
        edtEmail2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtEmail2.setForeground(new java.awt.Color(0, 0, 0));
        edtEmail2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEmail2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEmail2.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEmail2.setPreferredSize(new java.awt.Dimension(10, 20));
        edtEmail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEmail2ActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 240, 30));

        edtEmail3.setBackground(new java.awt.Color(251, 186, 0));
        edtEmail3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtEmail3.setForeground(new java.awt.Color(0, 0, 0));
        edtEmail3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEmail3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEmail3.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEmail3.setPreferredSize(new java.awt.Dimension(10, 20));
        edtEmail3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEmail3ActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtEmail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 240, 30));

        edtEmail4.setBackground(new java.awt.Color(251, 186, 0));
        edtEmail4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtEmail4.setForeground(new java.awt.Color(0, 0, 0));
        edtEmail4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEmail4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEmail4.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEmail4.setPreferredSize(new java.awt.Dimension(10, 20));
        edtEmail4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEmail4ActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtEmail4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 240, 30));

        edtEmail5.setBackground(new java.awt.Color(251, 186, 0));
        edtEmail5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtEmail5.setForeground(new java.awt.Color(0, 0, 0));
        edtEmail5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEmail5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEmail5.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEmail5.setPreferredSize(new java.awt.Dimension(10, 20));
        edtEmail5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEmail5ActionPerformed(evt);
            }
        });
        pnlSecundario.add(edtEmail5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 240, 30));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(251, 186, 0));
        jLabel3.setText("Informacoes pessoais:");
        pnlSecundario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(251, 186, 0));
        jLabel4.setText("Peso");
        pnlSecundario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(251, 186, 0));
        jLabel5.setText("Altura");
        pnlSecundario.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(251, 186, 0));
        jLabel6.setText("Massa Muscular");
        pnlSecundario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(251, 186, 0));
        jLabel7.setText("Gordura corporal");
        pnlSecundario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(251, 186, 0));
        jLabel8.setText("IMC(Indice de massa corporal)");
        pnlSecundario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        btnCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar.png"))); // NOI18N
        btnCadastrar.setText("CALCULAR");
        btnCadastrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        pnlSecundario.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 220, 60));

        pnlPrincipal.add(pnlSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 740, 420));

        btnSair.setBackground(new java.awt.Color(255, 102, 102));
        btnSair.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnSair.setForeground(new java.awt.Color(0, 0, 0));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icone sair.png"))); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 10, 140, 60));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoMenor.png"))); // NOI18N
        pnlPrincipal.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 130));

        btnTreinos.setBackground(new java.awt.Color(255, 255, 255));
        btnTreinos.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnTreinos.setForeground(new java.awt.Color(0, 0, 0));
        btnTreinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeTreinos.png"))); // NOI18N
        btnTreinos.setText("MANTER");
        btnTreinos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnTreinos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTreinosMouseClicked(evt);
            }
        });
        btnTreinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreinosActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnTreinos, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 350, 240, 60));

        btnTreinos1.setBackground(new java.awt.Color(255, 255, 255));
        btnTreinos1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnTreinos1.setForeground(new java.awt.Color(0, 0, 0));
        btnTreinos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeTreinos.png"))); // NOI18N
        btnTreinos1.setText("PERDER");
        btnTreinos1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnTreinos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTreinos1MouseClicked(evt);
            }
        });
        btnTreinos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreinos1ActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnTreinos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 160, 240, 60));

        btnTreinos2.setBackground(new java.awt.Color(255, 255, 255));
        btnTreinos2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnTreinos2.setForeground(new java.awt.Color(0, 0, 0));
        btnTreinos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeTreinos.png"))); // NOI18N
        btnTreinos2.setText("GANHAR");
        btnTreinos2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnTreinos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTreinos2MouseClicked(evt);
            }
        });
        btnTreinos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreinos2ActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnTreinos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 520, 240, 60));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 186, 0));
        jLabel2.setText("Saude");
        pnlPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background Saude.jpg"))); // NOI18N
        pnlPrincipal.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 1290, 730));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1285, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmailActionPerformed

    private void edtEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmail1ActionPerformed

    private void edtEmail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEmail2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmail2ActionPerformed

    private void edtEmail3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEmail3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmail3ActionPerformed

    private void edtEmail4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEmail4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmail4ActionPerformed

    private void edtEmail5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEmail5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEmail5ActionPerformed

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked

    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked

    }//GEN-LAST:event_btnSairMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnTreinosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTreinosMouseClicked
        new FrMenu().setVisible(true);
    }//GEN-LAST:event_btnTreinosMouseClicked

    private void btnTreinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTreinosActionPerformed

    private void btnTreinos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTreinos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTreinos1MouseClicked

    private void btnTreinos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreinos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTreinos1ActionPerformed

    private void btnTreinos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTreinos2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTreinos2MouseClicked

    private void btnTreinos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreinos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTreinos2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrSaude.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrSaude().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTreinos;
    private javax.swing.JButton btnTreinos1;
    private javax.swing.JButton btnTreinos2;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtEmail1;
    private javax.swing.JTextField edtEmail2;
    private javax.swing.JTextField edtEmail3;
    private javax.swing.JTextField edtEmail4;
    private javax.swing.JTextField edtEmail5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSecundario;
    // End of variables declaration//GEN-END:variables
}
