/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controlar.ControladorDeUsuario;
import java.util.List;
import modelo.Usuario;
import utilidade.Util;

/**
 *
 * @author aluno.saolucas
 */
public class FrTreinos extends javax.swing.JDialog {

    /**
     * Creates new form FrTreinos
     */
    public FrTreinos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlSuperior = new javax.swing.JPanel();
        lblObjetivo = new javax.swing.JLabel();
        lblNomeDoTreino1 = new javax.swing.JLabel();
        lblDuracao = new javax.swing.JLabel();
        edtDescricao = new javax.swing.JTextField();
        edtNomeTreino = new javax.swing.JTextField();
        edtObjetivo = new javax.swing.JTextField();
        lblNomeDoTreino2 = new javax.swing.JLabel();
        lblTreinoSegSex1 = new javax.swing.JLabel();
        edtDuracao = new javax.swing.JTextField();
        pnlInferior = new javax.swing.JPanel();
        lblTreinoSegSex = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblGrupoMuscular = new javax.swing.JLabel();
        lblEquipamento = new javax.swing.JLabel();
        lblDificuldade = new javax.swing.JLabel();
        lblCarga = new javax.swing.JLabel();
        lblSeries = new javax.swing.JLabel();
        lblRepeticoes = new javax.swing.JLabel();
        edtGrupoMuscular = new javax.swing.JTextField();
        edtNome = new javax.swing.JTextField();
        edtEquipamento = new javax.swing.JTextField();
        edtCarga = new javax.swing.JTextField();
        edtSeries = new javax.swing.JTextField();
        edtDificuldade = new javax.swing.JTextField();
        edtRepeticoes = new javax.swing.JTextField();
        edtCarga1 = new javax.swing.JTextField();
        lblCarga1 = new javax.swing.JLabel();
        lblRepeticoes1 = new javax.swing.JLabel();
        edtRepeticoes1 = new javax.swing.JTextField();
        edtSeries1 = new javax.swing.JTextField();
        lblSeries1 = new javax.swing.JLabel();
        lblDificuldade1 = new javax.swing.JLabel();
        edtDificuldade1 = new javax.swing.JTextField();
        edtGrupoMuscular1 = new javax.swing.JTextField();
        lblGrupoMuscular1 = new javax.swing.JLabel();
        lblEquipamento1 = new javax.swing.JLabel();
        edtEquipamento1 = new javax.swing.JTextField();
        edtNome1 = new javax.swing.JTextField();
        lblNome1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoMenor.png"))); // NOI18N
        pnlPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        pnlSuperior.setBackground(new java.awt.Color(255, 255, 255));
        pnlSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblObjetivo.setBackground(new java.awt.Color(0, 0, 0));
        lblObjetivo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblObjetivo.setForeground(new java.awt.Color(251, 186, 0));
        lblObjetivo.setText("Objetivo");
        pnlSuperior.add(lblObjetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        lblNomeDoTreino1.setBackground(new java.awt.Color(0, 0, 0));
        lblNomeDoTreino1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblNomeDoTreino1.setForeground(new java.awt.Color(251, 186, 0));
        lblNomeDoTreino1.setText("Descrição");
        pnlSuperior.add(lblNomeDoTreino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        lblDuracao.setBackground(new java.awt.Color(0, 0, 0));
        lblDuracao.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblDuracao.setForeground(new java.awt.Color(251, 186, 0));
        lblDuracao.setText("Duração");
        pnlSuperior.add(lblDuracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        edtDescricao.setBackground(new java.awt.Color(251, 186, 0));
        edtDescricao.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtDescricao.setForeground(new java.awt.Color(0, 0, 0));
        edtDescricao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtDescricao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtDescricao.setMinimumSize(new java.awt.Dimension(10, 20));
        edtDescricao.setPreferredSize(new java.awt.Dimension(10, 20));
        edtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDescricaoActionPerformed(evt);
            }
        });
        pnlSuperior.add(edtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 240, 80));

        edtNomeTreino.setBackground(new java.awt.Color(251, 186, 0));
        edtNomeTreino.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtNomeTreino.setForeground(new java.awt.Color(0, 0, 0));
        edtNomeTreino.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtNomeTreino.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtNomeTreino.setMinimumSize(new java.awt.Dimension(10, 20));
        edtNomeTreino.setPreferredSize(new java.awt.Dimension(10, 20));
        edtNomeTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeTreinoActionPerformed(evt);
            }
        });
        pnlSuperior.add(edtNomeTreino, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 300, 30));

        edtObjetivo.setBackground(new java.awt.Color(251, 186, 0));
        edtObjetivo.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtObjetivo.setForeground(new java.awt.Color(0, 0, 0));
        edtObjetivo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtObjetivo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtObjetivo.setMinimumSize(new java.awt.Dimension(10, 20));
        edtObjetivo.setPreferredSize(new java.awt.Dimension(10, 20));
        edtObjetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtObjetivoActionPerformed(evt);
            }
        });
        pnlSuperior.add(edtObjetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 300, 30));

        lblNomeDoTreino2.setBackground(new java.awt.Color(0, 0, 0));
        lblNomeDoTreino2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblNomeDoTreino2.setForeground(new java.awt.Color(251, 186, 0));
        lblNomeDoTreino2.setText("Nome do Treino");
        pnlSuperior.add(lblNomeDoTreino2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        lblTreinoSegSex1.setBackground(new java.awt.Color(0, 0, 0));
        lblTreinoSegSex1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblTreinoSegSex1.setForeground(new java.awt.Color(251, 186, 0));
        lblTreinoSegSex1.setText("TREINO DE SEG A SEX");
        pnlSuperior.add(lblTreinoSegSex1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        edtDuracao.setBackground(new java.awt.Color(251, 186, 0));
        edtDuracao.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtDuracao.setForeground(new java.awt.Color(0, 0, 0));
        edtDuracao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtDuracao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtDuracao.setMinimumSize(new java.awt.Dimension(10, 20));
        edtDuracao.setPreferredSize(new java.awt.Dimension(10, 20));
        edtDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDuracaoActionPerformed(evt);
            }
        });
        pnlSuperior.add(edtDuracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 300, 30));

        pnlPrincipal.add(pnlSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 870, 210));

        pnlInferior.setBackground(new java.awt.Color(255, 255, 255));
        pnlInferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTreinoSegSex.setBackground(new java.awt.Color(0, 0, 0));
        lblTreinoSegSex.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblTreinoSegSex.setForeground(new java.awt.Color(251, 186, 0));
        lblTreinoSegSex.setText("EXERCÍCIOS");
        pnlInferior.add(lblTreinoSegSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        lblNome.setBackground(new java.awt.Color(0, 0, 0));
        lblNome.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblNome.setForeground(new java.awt.Color(251, 186, 0));
        lblNome.setText("Nome");
        pnlInferior.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        lblGrupoMuscular.setBackground(new java.awt.Color(0, 0, 0));
        lblGrupoMuscular.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblGrupoMuscular.setForeground(new java.awt.Color(251, 186, 0));
        lblGrupoMuscular.setText("Grupo Muscular");
        pnlInferior.add(lblGrupoMuscular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        lblEquipamento.setBackground(new java.awt.Color(0, 0, 0));
        lblEquipamento.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblEquipamento.setForeground(new java.awt.Color(251, 186, 0));
        lblEquipamento.setText("Equipamento");
        pnlInferior.add(lblEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        lblDificuldade.setBackground(new java.awt.Color(0, 0, 0));
        lblDificuldade.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblDificuldade.setForeground(new java.awt.Color(251, 186, 0));
        lblDificuldade.setText("Dificuldade");
        pnlInferior.add(lblDificuldade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        lblCarga.setBackground(new java.awt.Color(0, 0, 0));
        lblCarga.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblCarga.setForeground(new java.awt.Color(251, 186, 0));
        lblCarga.setText("Carga");
        pnlInferior.add(lblCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        lblSeries.setBackground(new java.awt.Color(0, 0, 0));
        lblSeries.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblSeries.setForeground(new java.awt.Color(251, 186, 0));
        lblSeries.setText("Series");
        pnlInferior.add(lblSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        lblRepeticoes.setBackground(new java.awt.Color(0, 0, 0));
        lblRepeticoes.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblRepeticoes.setForeground(new java.awt.Color(251, 186, 0));
        lblRepeticoes.setText("Repetições");
        pnlInferior.add(lblRepeticoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        edtGrupoMuscular.setBackground(new java.awt.Color(251, 186, 0));
        edtGrupoMuscular.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtGrupoMuscular.setForeground(new java.awt.Color(0, 0, 0));
        edtGrupoMuscular.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtGrupoMuscular.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtGrupoMuscular.setMinimumSize(new java.awt.Dimension(10, 20));
        edtGrupoMuscular.setPreferredSize(new java.awt.Dimension(10, 20));
        edtGrupoMuscular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtGrupoMuscularActionPerformed(evt);
            }
        });
        pnlInferior.add(edtGrupoMuscular, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 300, 30));

        edtNome.setBackground(new java.awt.Color(251, 186, 0));
        edtNome.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtNome.setForeground(new java.awt.Color(0, 0, 0));
        edtNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtNome.setMinimumSize(new java.awt.Dimension(10, 20));
        edtNome.setPreferredSize(new java.awt.Dimension(10, 20));
        edtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeActionPerformed(evt);
            }
        });
        pnlInferior.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 300, 30));

        edtEquipamento.setBackground(new java.awt.Color(251, 186, 0));
        edtEquipamento.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtEquipamento.setForeground(new java.awt.Color(0, 0, 0));
        edtEquipamento.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEquipamento.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEquipamento.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEquipamento.setPreferredSize(new java.awt.Dimension(10, 20));
        edtEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEquipamentoActionPerformed(evt);
            }
        });
        pnlInferior.add(edtEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 300, 30));

        edtCarga.setBackground(new java.awt.Color(251, 186, 0));
        edtCarga.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtCarga.setForeground(new java.awt.Color(0, 0, 0));
        edtCarga.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtCarga.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtCarga.setMinimumSize(new java.awt.Dimension(10, 20));
        edtCarga.setPreferredSize(new java.awt.Dimension(10, 20));
        edtCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCargaActionPerformed(evt);
            }
        });
        pnlInferior.add(edtCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 300, 30));

        edtSeries.setBackground(new java.awt.Color(251, 186, 0));
        edtSeries.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtSeries.setForeground(new java.awt.Color(0, 0, 0));
        edtSeries.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtSeries.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtSeries.setMinimumSize(new java.awt.Dimension(10, 20));
        edtSeries.setPreferredSize(new java.awt.Dimension(10, 20));
        edtSeries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtSeriesActionPerformed(evt);
            }
        });
        pnlInferior.add(edtSeries, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 300, 30));

        edtDificuldade.setBackground(new java.awt.Color(251, 186, 0));
        edtDificuldade.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtDificuldade.setForeground(new java.awt.Color(0, 0, 0));
        edtDificuldade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtDificuldade.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtDificuldade.setMinimumSize(new java.awt.Dimension(10, 20));
        edtDificuldade.setPreferredSize(new java.awt.Dimension(10, 20));
        edtDificuldade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDificuldadeActionPerformed(evt);
            }
        });
        pnlInferior.add(edtDificuldade, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 300, 30));

        edtRepeticoes.setBackground(new java.awt.Color(251, 186, 0));
        edtRepeticoes.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtRepeticoes.setForeground(new java.awt.Color(0, 0, 0));
        edtRepeticoes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtRepeticoes.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtRepeticoes.setMinimumSize(new java.awt.Dimension(10, 20));
        edtRepeticoes.setPreferredSize(new java.awt.Dimension(10, 20));
        edtRepeticoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtRepeticoesActionPerformed(evt);
            }
        });
        pnlInferior.add(edtRepeticoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 300, 30));

        edtCarga1.setBackground(new java.awt.Color(251, 186, 0));
        edtCarga1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtCarga1.setForeground(new java.awt.Color(0, 0, 0));
        edtCarga1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtCarga1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtCarga1.setMinimumSize(new java.awt.Dimension(10, 20));
        edtCarga1.setPreferredSize(new java.awt.Dimension(10, 20));
        edtCarga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCarga1ActionPerformed(evt);
            }
        });
        pnlInferior.add(edtCarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, 300, 30));

        lblCarga1.setBackground(new java.awt.Color(0, 0, 0));
        lblCarga1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblCarga1.setForeground(new java.awt.Color(251, 186, 0));
        lblCarga1.setText("Carga");
        pnlInferior.add(lblCarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, -1, -1));

        lblRepeticoes1.setBackground(new java.awt.Color(0, 0, 0));
        lblRepeticoes1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblRepeticoes1.setForeground(new java.awt.Color(251, 186, 0));
        lblRepeticoes1.setText("Repetições");
        pnlInferior.add(lblRepeticoes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        edtRepeticoes1.setBackground(new java.awt.Color(251, 186, 0));
        edtRepeticoes1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtRepeticoes1.setForeground(new java.awt.Color(0, 0, 0));
        edtRepeticoes1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtRepeticoes1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtRepeticoes1.setMinimumSize(new java.awt.Dimension(10, 20));
        edtRepeticoes1.setPreferredSize(new java.awt.Dimension(10, 20));
        edtRepeticoes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtRepeticoes1ActionPerformed(evt);
            }
        });
        pnlInferior.add(edtRepeticoes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 300, 30));

        edtSeries1.setBackground(new java.awt.Color(251, 186, 0));
        edtSeries1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtSeries1.setForeground(new java.awt.Color(0, 0, 0));
        edtSeries1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtSeries1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtSeries1.setMinimumSize(new java.awt.Dimension(10, 20));
        edtSeries1.setPreferredSize(new java.awt.Dimension(10, 20));
        edtSeries1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtSeries1ActionPerformed(evt);
            }
        });
        pnlInferior.add(edtSeries1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 300, 30));

        lblSeries1.setBackground(new java.awt.Color(0, 0, 0));
        lblSeries1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblSeries1.setForeground(new java.awt.Color(251, 186, 0));
        lblSeries1.setText("Series");
        pnlInferior.add(lblSeries1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, -1, -1));

        lblDificuldade1.setBackground(new java.awt.Color(0, 0, 0));
        lblDificuldade1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblDificuldade1.setForeground(new java.awt.Color(251, 186, 0));
        lblDificuldade1.setText("Dificuldade");
        pnlInferior.add(lblDificuldade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, -1, -1));

        edtDificuldade1.setBackground(new java.awt.Color(251, 186, 0));
        edtDificuldade1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtDificuldade1.setForeground(new java.awt.Color(0, 0, 0));
        edtDificuldade1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtDificuldade1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtDificuldade1.setMinimumSize(new java.awt.Dimension(10, 20));
        edtDificuldade1.setPreferredSize(new java.awt.Dimension(10, 20));
        edtDificuldade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDificuldade1ActionPerformed(evt);
            }
        });
        pnlInferior.add(edtDificuldade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 300, 30));

        edtGrupoMuscular1.setBackground(new java.awt.Color(251, 186, 0));
        edtGrupoMuscular1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtGrupoMuscular1.setForeground(new java.awt.Color(0, 0, 0));
        edtGrupoMuscular1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtGrupoMuscular1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtGrupoMuscular1.setMinimumSize(new java.awt.Dimension(10, 20));
        edtGrupoMuscular1.setPreferredSize(new java.awt.Dimension(10, 20));
        edtGrupoMuscular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtGrupoMuscular1ActionPerformed(evt);
            }
        });
        pnlInferior.add(edtGrupoMuscular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 300, 30));

        lblGrupoMuscular1.setBackground(new java.awt.Color(0, 0, 0));
        lblGrupoMuscular1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblGrupoMuscular1.setForeground(new java.awt.Color(251, 186, 0));
        lblGrupoMuscular1.setText("Grupo Muscular");
        pnlInferior.add(lblGrupoMuscular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));

        lblEquipamento1.setBackground(new java.awt.Color(0, 0, 0));
        lblEquipamento1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblEquipamento1.setForeground(new java.awt.Color(251, 186, 0));
        lblEquipamento1.setText("Equipamento");
        pnlInferior.add(lblEquipamento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        edtEquipamento1.setBackground(new java.awt.Color(251, 186, 0));
        edtEquipamento1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtEquipamento1.setForeground(new java.awt.Color(0, 0, 0));
        edtEquipamento1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtEquipamento1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtEquipamento1.setMinimumSize(new java.awt.Dimension(10, 20));
        edtEquipamento1.setPreferredSize(new java.awt.Dimension(10, 20));
        edtEquipamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtEquipamento1ActionPerformed(evt);
            }
        });
        pnlInferior.add(edtEquipamento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 300, 30));

        edtNome1.setBackground(new java.awt.Color(251, 186, 0));
        edtNome1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        edtNome1.setForeground(new java.awt.Color(0, 0, 0));
        edtNome1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edtNome1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtNome1.setMinimumSize(new java.awt.Dimension(10, 20));
        edtNome1.setPreferredSize(new java.awt.Dimension(10, 20));
        edtNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNome1ActionPerformed(evt);
            }
        });
        pnlInferior.add(edtNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 300, 30));

        lblNome1.setBackground(new java.awt.Color(0, 0, 0));
        lblNome1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(251, 186, 0));
        lblNome1.setText("Nome");
        pnlInferior.add(lblNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, -1, -1));

        pnlPrincipal.add(pnlInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 1210, 420));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/treinos.jpg"))); // NOI18N
        background.setText("jLabel1");
        pnlPrincipal.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDescricaoActionPerformed

    private void edtNomeTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeTreinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeTreinoActionPerformed

    private void edtObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtObjetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtObjetivoActionPerformed

    private void edtDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDuracaoActionPerformed

    private void edtCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCargaActionPerformed

    private void edtSeriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtSeriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtSeriesActionPerformed

    private void edtRepeticoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtRepeticoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtRepeticoesActionPerformed

    private void edtDificuldadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDificuldadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDificuldadeActionPerformed

    private void edtGrupoMuscularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtGrupoMuscularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtGrupoMuscularActionPerformed

    private void edtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeActionPerformed

    private void edtEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEquipamentoActionPerformed

    private void edtCarga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCarga1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCarga1ActionPerformed

    private void edtRepeticoes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtRepeticoes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtRepeticoes1ActionPerformed

    private void edtSeries1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtSeries1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtSeries1ActionPerformed

    private void edtDificuldade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDificuldade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDificuldade1ActionPerformed

    private void edtGrupoMuscular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtGrupoMuscular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtGrupoMuscular1ActionPerformed

    private void edtEquipamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtEquipamento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtEquipamento1ActionPerformed

    private void edtNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNome1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           this.setIconImage(Util.getIcone());

    //Carregar os dados do usuário
    ControladorDeUsuario controller = new ControladorDeUsuario();

    //consultei os usuários com o código igual ao que recebi 
    // na tela de consulta
    //List<Usuario> lista = controller.consultar(0, String.valueOf(pkUsuario));

    Usuario usu = null;
    //usu = lista.get(0);

    //Preencher os campos como a variável usu
   // edtCodigo.setText(String.valueOf(usu.getPkUsuario()));
    //edtNome.setText(usu.getNome());
   // edtEmail.setText(usu.getEmail());
    //edtDataNascimento.setText(
          //  Util.converterDateToString(usu.getDataNascimento()));
   // chkAtivo.setSelected(usu.isAtivo());
   // imgFoto.setIcon(usu.getImagem());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrTreinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrTreinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrTreinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrTreinos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrTreinos dialog = new FrTreinos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField edtCarga;
    private javax.swing.JTextField edtCarga1;
    private javax.swing.JTextField edtDescricao;
    private javax.swing.JTextField edtDificuldade;
    private javax.swing.JTextField edtDificuldade1;
    private javax.swing.JTextField edtDuracao;
    private javax.swing.JTextField edtEquipamento;
    private javax.swing.JTextField edtEquipamento1;
    private javax.swing.JTextField edtGrupoMuscular;
    private javax.swing.JTextField edtGrupoMuscular1;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtNome1;
    private javax.swing.JTextField edtNomeTreino;
    private javax.swing.JTextField edtObjetivo;
    private javax.swing.JTextField edtRepeticoes;
    private javax.swing.JTextField edtRepeticoes1;
    private javax.swing.JTextField edtSeries;
    private javax.swing.JTextField edtSeries1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCarga;
    private javax.swing.JLabel lblCarga1;
    private javax.swing.JLabel lblDificuldade;
    private javax.swing.JLabel lblDificuldade1;
    private javax.swing.JLabel lblDuracao;
    private javax.swing.JLabel lblEquipamento;
    private javax.swing.JLabel lblEquipamento1;
    private javax.swing.JLabel lblGrupoMuscular;
    private javax.swing.JLabel lblGrupoMuscular1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNomeDoTreino1;
    private javax.swing.JLabel lblNomeDoTreino2;
    private javax.swing.JLabel lblObjetivo;
    private javax.swing.JLabel lblRepeticoes;
    private javax.swing.JLabel lblRepeticoes1;
    private javax.swing.JLabel lblSeries;
    private javax.swing.JLabel lblSeries1;
    private javax.swing.JLabel lblTreinoSegSex;
    private javax.swing.JLabel lblTreinoSegSex1;
    private javax.swing.JPanel pnlInferior;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSuperior;
    // End of variables declaration//GEN-END:variables
}
